USE gestor_inc;

INSERT INTO usuarios (nombre_usuario, contrasena, password_hash) VALUES
('root', '1234', '$2y$10$EXAMPLEHASHyourswitchthis');

-- Generar 50 tickets de ejemplo
INSERT INTO tickets (nombre_ticket, descripcion, prioridad, estado) VALUES
('Incidencia 1','Descripcion ejemplo 1','low','abierta'),
('Incidencia 2','Descripcion ejemplo 2','medium','abierta'),
('Incidencia 3','Descripcion ejemplo 3','high','cerrada'),
('Incidencia 4','Descripcion ejemplo 4','medium','abierta'),
('Incidencia 5','Descripcion ejemplo 5','low','cerrada'),
('Incidencia 6','Descripcion ejemplo 6','high','abierta'),
('Incidencia 7','Descripcion ejemplo 7','low','abierta'),
('Incidencia 8','Descripcion ejemplo 8','medium','cerrada'),
('Incidencia 9','Descripcion ejemplo 9','high','abierta'),
('Incidencia 10','Descripcion ejemplo 10','medium','abierta'),
('Incidencia 11','Descripcion ejemplo 11','low','abierta'),
('Incidencia 12','Descripcion ejemplo 12','high','cerrada'),
('Incidencia 13','Descripcion ejemplo 13','medium','abierta'),
('Incidencia 14','Descripcion ejemplo 14','low','abierta'),
('Incidencia 15','Descripcion ejemplo 15','high','abierta'),
('Incidencia 16','Descripcion ejemplo 16','medium','cerrada'),
('Incidencia 17','Descripcion ejemplo 17','low','abierta'),
('Incidencia 18','Descripcion ejemplo 18','medium','abierta'),
('Incidencia 19','Descripcion ejemplo 19','high','cerrada'),
('Incidencia 20','Descripcion ejemplo 20','low','abierta'),
('Incidencia 21','Descripcion ejemplo 21','medium','abierta'),
('Incidencia 22','Descripcion ejemplo 22','high','abierta'),
('Incidencia 23','Descripcion ejemplo 23','low','cerrada'),
('Incidencia 24','Descripcion ejemplo 24','medium','abierta'),
('Incidencia 25','Descripcion ejemplo 25','high','abierta'),
('Incidencia 26','Descripcion ejemplo 26','low','abierta'),
('Incidencia 27','Descripcion ejemplo 27','medium','cerrada'),
('Incidencia 28','Descripcion ejemplo 28','high','abierta'),
('Incidencia 29','Descripcion ejemplo 29','low','abierta'),
('Incidencia 30','Descripcion ejemplo 30','medium','cerrada'),
('Incidencia 31','Descripcion ejemplo 31','high','abierta'),
('Incidencia 32','Descripcion ejemplo 32','low','abierta'),
('Incidencia 33','Descripcion ejemplo 33','medium','abierta'),
('Incidencia 34','Descripcion ejemplo 34','high','cerrada'),
('Incidencia 35','Descripcion ejemplo 35','low','abierta'),
('Incidencia 36','Descripcion ejemplo 36','medium','abierta'),
('Incidencia 37','Descripcion ejemplo 37','high','abierta'),
('Incidencia 38','Descripcion ejemplo 38','low','cerrada'),
('Incidencia 39','Descripcion ejemplo 39','medium','abierta'),
('Incidencia 40','Descripcion ejemplo 40','high','abierta'),
('Incidencia 41','Descripcion ejemplo 41','low','abierta'),
('Incidencia 42','Descripcion ejemplo 42','medium','cerrada'),
('Incidencia 43','Descripcion ejemplo 43','high','abierta'),
('Incidencia 44','Descripcion ejemplo 44','low','abierta'),
('Incidencia 45','Descripcion ejemplo 45','medium','abierta'),
('Incidencia 46','Descripcion ejemplo 46','high','cerrada'),
('Incidencia 47','Descripcion ejemplo 47','low','abierta'),
('Incidencia 48','Descripcion ejemplo 48','medium','abierta'),
('Incidencia 49','Descripcion ejemplo 49','high','abierta'),
('Incidencia 50','Descripcion ejemplo 50','low','abierta');